name: Capitalism
version: '${project.version}'
main: xyz.jayphen.capitalism.Capitalism
api-version: 1.18
depend: [ Vault, WorldEdit, BlueMap ]
commands:
  balance:
    description: View your balance
    permission: core.bal
    usage: /<command>
    aliases:
      - bal
  cheapest:
    description: Find the cheapest shop selling a specific item
    permission: core.cheapest
    usage: /<command> <item_name>
    aliases:
      - find
      - cheap
      - searchfor
  pay:
    description: Pay a player a certain amount of cash.
    permission: core.pay
    usage: /<command> <player> <amount>
    aliases:
      - send
      - transfer
      - donate
  profile:
    description: View information about your player and account
    permission: core.profile
    aliases:
      - p
      - self
      - prof
      - stats
  land:
    description: Allows you to manage the properties you own
    permission: core.land
    aliases:
      - landlord
      - l
  hud:
    description: Toggles the scoreboard hud, showcasing various stats
    permission: core.hud
  admin:
    permission: core.admin
  matrix:
    permission: core.admin
  aac:
    permission: core.admin
  spartan:
    permission: core.admin
  vulcan:
    permission: core.admin
  ncp:
    permission: core.admin
