name: Capitalism
version: '${project.version}'
main: xyz.jayphen.capitalism.Capitalism
api-version: 1.18
depend:
  - Vault
commands:
  balance:
    description: View your balance
    permission: core.bal
    usage: /<command>
    aliases:
      - bal
  pay:
    description: Pay a player a certain amount of cash.
    permission: core.pay
    usage: /<command> <player> <amount>
